"""add detections and processing_runs tables

Revision ID: 6a67b8944114
Revises: 8382003b60c1
Create Date: 2025-12-08 21:54:27.101633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a67b8944114'
down_revision: Union[str, None] = '8382003b60c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('frame_idx', sa.Integer(), nullable=False, comment='Frame number in the video'),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False, comment='Timestamp in milliseconds'),
    sa.Column('track_id', sa.Integer(), nullable=True, comment='Tracking ID assigned by ByteTrack'),
    sa.Column('class_name', sa.String(length=50), nullable=False, comment='Detected class (car, truck, etc.)'),
    sa.Column('class_id', sa.Integer(), nullable=False, comment='YOLO class ID'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Detection confidence score'),
    sa.Column('bbox_x', sa.Float(), nullable=False, comment='Top-left X coordinate'),
    sa.Column('bbox_y', sa.Float(), nullable=False, comment='Top-left Y coordinate'),
    sa.Column('bbox_w', sa.Float(), nullable=False, comment='Bounding box width'),
    sa.Column('bbox_h', sa.Float(), nullable=False, comment='Bounding box height'),
    sa.Column('center_x', sa.Float(), nullable=False, comment='Center X coordinate'),
    sa.Column('center_y', sa.Float(), nullable=False, comment='Center Y coordinate'),
    sa.Column('speed_mph', sa.Float(), nullable=True, comment='Estimated speed in mph'),
    sa.Column('world_x', sa.Float(), nullable=True, comment='World X coordinate (meters)'),
    sa.Column('world_y', sa.Float(), nullable=True, comment='World Y coordinate (meters)'),
    sa.Column('extra', sa.JSON(), nullable=True, comment='Additional detection metadata'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detections_frame_idx', 'detections', ['frame_idx'], unique=False)
    op.create_index('ix_detections_project_frame', 'detections', ['project_id', 'frame_idx'], unique=False)
    op.create_index('ix_detections_project_track', 'detections', ['project_id', 'track_id'], unique=False)
    op.create_table('processing_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='pending, processing, completed, failed'),
    sa.Column('video_uri', sa.String(length=500), nullable=False, comment='Cloudinary video URL'),
    sa.Column('total_frames', sa.Integer(), nullable=True, comment='Total frames in video'),
    sa.Column('processed_frames', sa.Integer(), nullable=True, comment='Frames processed so far'),
    sa.Column('detection_count', sa.Integer(), nullable=True, comment='Total detections found'),
    sa.Column('unique_tracks', sa.Integer(), nullable=True, comment='Unique vehicles tracked'),
    sa.Column('config', sa.JSON(), nullable=True, comment='Processing configuration used'),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_runs')
    op.drop_index('ix_detections_project_track', table_name='detections')
    op.drop_index('ix_detections_project_frame', table_name='detections')
    op.drop_index('ix_detections_frame_idx', table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###
