"""add homography tables

Revision ID: f90222a2f73f
Revises: 9a05a949b6bf
Create Date: 2025-12-12 11:42:33.245264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f90222a2f73f'
down_revision: Union[str, None] = '9a05a949b6bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homography_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('solved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('homography_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('matrix_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reprojection_error', sa.Float(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['homography_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homography_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('image_x_norm', sa.Float(), nullable=False),
    sa.Column('image_y_norm', sa.Float(), nullable=False),
    sa.Column('map_lat', sa.Float(), nullable=False),
    sa.Column('map_lng', sa.Float(), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['homography_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_ai_summaries_project_id', table_name='ai_summaries')
    op.alter_column('detections', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_detections_project_id'), 'detections', ['project_id'], unique=False)
    op.create_index(op.f('ix_detections_track_id'), 'detections', ['track_id'], unique=False)
    op.drop_constraint('detections_project_id_fkey', 'detections', type_='foreignkey')
    op.alter_column('processing_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('processing_runs', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('processing_runs', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_processing_runs_project_id'), 'processing_runs', ['project_id'], unique=False)
    op.drop_constraint('processing_runs_project_id_fkey', 'processing_runs', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('processing_runs_project_id_fkey', 'processing_runs', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_processing_runs_project_id'), table_name='processing_runs')
    op.alter_column('processing_runs', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('processing_runs', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('processing_runs', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_foreign_key('detections_project_id_fkey', 'detections', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_detections_track_id'), table_name='detections')
    op.drop_index(op.f('ix_detections_project_id'), table_name='detections')
    op.alter_column('detections', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.create_index('ix_ai_summaries_project_id', 'ai_summaries', ['project_id'], unique=False)
    op.drop_table('homography_pairs')
    op.drop_table('homography_models')
    op.drop_table('homography_sessions')
    # ### end Alembic commands ###
